### ISSUE TITLE
Change the published topic

### ISSUE THREAD

**Issue by tedtms** [neilenns/ambientweather2mqtt#110]
Hello! Cool project you have here!

I'm actually using it to push the converted ambientweather MQTT data to a regular mosquitto server, from which I'm planning to pull it into a Grafana dashboard. I noticed when exploring the published data that the topic is "homeassistant". Is it possible to make that topic configurable?

Thanks!
Ted

**Comment by neilenns** [comment]
It's not currently configurable but it wouldn't be too hard to make it settable via an environment variable. Would that work?

**Comment by tedtms** [comment]
That would be perfect, thank you!

**Comment by neilenns** [comment]
Ok the latest Docker image should have this now. Set the `TOPIC_ROOT` environment variable to whatever string you want to use instead.
