### ISSUE TITLE
Lightning Sensor Values - Feature

### ISSUE THREAD

**Issue by ryanherbison** [neilenns/ambientweather2mqtt#114]
Hi Neil

Would love to get the lightning data from my WS-5000, recently added the lightning detector module. Not sure if lightning_time is important since the record will get timestamped regardless. Mostly I want to graph the daily count and distance, so I can setup some sort of alarm for lightning approaching, especially detecting severe approaching events. Somewhat important when one lives at 7000ft on a mountain.

Here is the output from my weather station and I copied some info on the fields below from ambientweather. There is also a "batt_lightning" for the battery status.

https://ambientweather.com/faqs/question/view/id/1857/

GET /data/?stationtype=AMBWeatherPro_V5.1.1&PASSKEY=48:55:19:XX:XX:XX&dateutc=2023-08-09+03:06:27&tempf=63.0&humidity=91&windspeedmph=0.00&windgustmph=1.57&maxdailygust=16.11&winddir=202&winddir_avg10m=193&uv=0&solarradiation=0.00&hourlyrainin=0.000&eventrainin=0.433&dailyrainin=0.433&weeklyrainin=1.087&monthlyrainin=2.555&yearlyrainin=13.933&battout=1&battrain=1&tempinf=70.9&humidityin=73&baromrelin=23.211&baromabsin=23.211&battin=1&soilhum1=0&soilhum2=0&battsm1=1&battsm2=1&lightning_day=9&lightning_time=1691549949&lightning_distance=34&batt_lightning=0 HTTP/1.1

94 	lightning_time 		Last strike date and time 	Seconds since January 1, 1970 	 
95 	lightning_day 		Number of strikes per day 	count 	 
96 	lightning_distance 	Distance of last strike 	float 	km
29 | batt_lightning | Lighting detector battery | discrete 0 or 1

Thanks

**Comment by neilenns** [comment]
Thank you for providing the sample data url and link to the Ambient Weather documentation! This is implemented:

![image](https://github.com/neilenns/ambientweather2mqtt/assets/9524118/9ceb6b4a-f8d6-484c-9777-d2f0f84420e0)

![image](https://github.com/neilenns/ambientweather2mqtt/assets/9524118/277c68e1-e9ca-46f5-b2c4-1a29b48ae164)

The updated release is live and will eventually show in Home Assistant. You can force Home Assistant to check for the update by going to the Add-On Store, selecting ... in the top right, then `Check for updates`.
