### ISSUE TITLE
eventDate still returning state_class of 'measurement' - causing errors in HomeAssistant

### ISSUE THREAD

**Issue by KidA001** [neilenns/ambientweather2mqtt#119]
I'm running the latest version of the image `ghcr.io/neilenns/ambientweather2mqtt - 788c2bc602d2`

It looks like there were some attempts to set the write state/class for this sensor in https://github.com/neilenns/ambientweather2mqtt/issues/99, but HA is still throwing an error

```
Entity sensor.eventdate (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22
```

When I look at the MQTT object for this sensor it's showing:
```json
{
  "device": {
    "identifiers": [
      "AW_C45BBE5D103B"
    ],
    "manufacturer": "Ambient Weather",
    "name": "ambientweather2mqtt",
    "model": "Ambient Weather Station"
  },
  "device_class": "timestamp",
  "state_class": "measurement",
  "icon": "mdi:clock-outline",
  "name": "eventDate",
  "unique_id": "C45BBE5D103B_eventDate",
  "state_topic": "homeassistant/sensor/C45BBE5D103B/eventDate/state"
}
```

`state_class` should be set to `None` according to HomeAssistant. It looks like in `entity.ts` it defaults `state_class` to `measurement` for all entities instead of accepting a variable. Maybe it can accept a variable if provided and otherwise default to `measurement`?

**Comment by KidA001** [comment]
I have this PR up if it's helpful: https://github.com/neilenns/ambientweather2mqtt/pull/120

**Comment by neilenns** [comment]
I swear, this change on the HomeAssistant side was the most infuriating change ever, and they've made some pretty infuriating ones in the past 😒

I'll take a look at the PR shortly, thank you!

**Comment by neilenns** [comment]
Ok this is released! Thank you for the contribution!
