### ISSUE TITLE
Issue supporting my observer2.2.6

### ISSUE THREAD

**Issue by cybernard** [neilenns/ambientweather2mqtt#124]
I tried configuring my observer2 to your home assistant add on.
I used tcpdump to capture raw data, and captured a packet

Then I telneted to homeassistant:8130  (which is the port your mqtt add on.
I pasted in the following and hit enter twice and it accepted the record.

GET /data/?MAC=11:22:33:44:55:66&stationtype=OBSERVERIP2_V2.2.6&dateutc=2023-12-07+01%3A07%3A10&tempf=35.96&humidity=81&windspeedmph=3.58&windgustmph=10.74&maxdailygust=14.76&winddir=30&winddir_avg10m=16&uv=0&solarradiation=0.00&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.378&monthlyrainin=0.677&yearlyrainin=9.638&totalrainin=9.638&battout=1&battrain=1&tempinf=69.08&humidityin=29&baromrelin=29.808&baromabsin=29.247&battin=1&temp2f=35.96&humidity2=81&batt2=1&lightning_day=9&lightning_time=1701904871&lightning_distance=14&batt_lightning=0&pm25=38.0&pm25_24h=29.1&aqi_pm25=107&aqi_pm25_24h=87&batt_25=1 HTTP/1.1  
Host: <redacted>
Connection:close  
User-Agent:OBSERVERIP2

The mac has been replaced.

It seems to be almost working, but there seems to be some minor reason your add on isn't reading the data automatically.

The log file doesn't indicate it is receiving any data at all, but nc or netcat can receive the data.

The very first part of the connection isn't logged so I can't tell what going wrong.

**Comment by neilenns** [comment]
I tested the data you provided by manually going to the URL and it works fine:

![image](https://github.com/neilenns/ambientweather2mqtt/assets/9524118/5c8107f7-5539-4c95-a676-34858fcd47b3)

**Comment by cybernard** [comment]
yes it works over telnet, but over http i notice a http 400 error.
so I first verify the observer was working with nc.

nc -l -p 8130

and pointed the observer2 at the ip address of another computer and it works.

Then I went into home assistant and launched a "terminal" add-on.

After than I again launch nc -l -p 8130

Again that part works on the home assistant pi 4.

nc displays the contents of the message.

Then I cancel nc, and restart your ambient2mgtt addon on 8130

If I type telnet <ip> 8130  <paste from nc>  
Then hit enter 2 times it works.

However, your addon is not accepting a connection from the observer2 for me directly.

**Comment by neilenns** [comment]
Have you enabled verbose logging in the settings for the add-on? If verbose logging is enabled it will log a message every time it receives a GET request on the /data endpoint.

**Comment by cybernard** [comment]
it not a firewall or weather station issue.
I have the weather station pointed at home assistant.  When your addon is stopped and I run "nc -l -p 8130" (on the home assistant device via terminal addon) netcat displays what the weather station is sending.

So if netcat can receive it so should your add-on.

**Comment by neilenns** [comment]
I'm afraid I don't have any other suggestions to offer. The addon is fine with the URL you provided on my end, which indicates the format of the data from the weather station is correct and handled by the addon. Since I don't have access to your exact setup there's not much else I can do to assist.

**Comment by cybernard** [comment]
Yes, but I had to use nc to intercept the data and then telnet manually to send the data to your add-on.  Which python script and line number establishes the listen on the port.  So I can investigate that.

**Comment by cybernard** [comment]
![image](https://github.com/neilenns/ambientweather2mqtt/assets/15042777/ca90641b-dbd1-4d6b-b556-f9201aa16e60)

So if I do this I can get it to work.  So there's a bunch of incompatible headers tacked onto the incoming packet.
