### ISSUE TITLE
Connect with HA Docker

### ISSUE THREAD

**Issue by Afar077** [neilenns/ambientweather2mqtt#126]
I installed the docker on my server running MQTT broker and HA dockers. Ambientweather2MQTT docker is connecting to MQTT broker but sensors not showing in HA docker via MQTT integration. Is it possible to use docker with HA docker and not just HAOS or supervisor?

**Comment by neilenns** [comment]
It works fine as a standalone Docker image, that's how it was originally developed.

If you aren't seeing sensors it means the Docker container never got any incoming data from your Ambient Weather station. Enable verbose logging and that will show if it ever receives a message from the station.

If you don't see any log messages saying it received data it's probably a Docker container misconfiguration where the port isn't exposed out of the Docker container correctly.

**Comment by Afar077** [comment]
I'm starting out with custom docker configuations so not sure yet how to enable verbose logging. Can I do this by adding an extra variable to my .env file? 

As for the port being not exposed, that's probably the case but I'm not sure how I got there. I'm running this on Unraid OS and did not modify anything from the original image. My port mapping looks good.

**Comment by neilenns** [comment]
> I'm starting out with custom docker configuations so not sure yet how to enable verbose logging. Can I do this by adding an extra variable to my .env file?

Yes, just set `VERBOSE` to `true`. I realize now this isn't listed in the readme 🤦‍♂️

Post a screenshot of how you have the Docker container configured. I'm not super familiar with unraid but maybe I'll see something.

**Comment by Afar077** [comment]
OK so I added the Verbose to TRUE but still nothing from the sensors. Must be a connection issue like you said. Here are the screenshots of the config below. I also added the screenshot from my Ambient Weather config.

In the Ambient weather config we have to set the path to /data/? but I noticed that unlike other dockers that I have this one did not create a directory for the yaml file or other config file on my server. I created a custom folder and added the path in the config to point to it. Did not seem to make a difference though. 

![image](https://github.com/neilenns/ambientweather2mqtt/assets/107782667/05419294-4719-4914-82fe-69196d621604)
![image](https://github.com/neilenns/ambientweather2mqtt/assets/107782667/7042a4e7-7d0d-407a-b754-a643bea0709e)
![image](https://github.com/neilenns/ambientweather2mqtt/assets/107782667/bde7a4d5-a5d2-441d-811c-0a8bf984446f)

**Comment by neilenns** [comment]
Try accessing the URL directly from your browser. You should get back an `Ok`.

https://192.168.1.16:8132/data/?stationtype=AMBWeatherV4.2.9&PASSKEY=11:22:33:44:55:66&dateutc=2021-07-01+20:34:06&tempinf=73.0&humidityin=56&baromrelin=29.900&baromabsin=29.513&tempf=68.2&battout=1&humidity=66&winddir=358&windspeedmph=0.0&windgustmph=0.0&maxdailygust=3.4&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.000&totalrainin=0.000&solarradiation=93.58&uv=0&batt_co2=1

**Comment by neilenns** [comment]
I pushed a new release that adds some increased logging. You can now enable "http" level logging in the configuration for the add-on and that will clearly show in the log if the add-on is ever getting a call from your weather station.

**Comment by Afar077** [comment]
So I had to modify your link for it to work. I removed the 's' of https. It works with http and gives me an ok.  I went in my ambienweather station and made sure the IP was http and https so it should not be an issue. 

Just updated the docker but I don't have the new setting in my config. I'll have to add it manually. Do you have the name of the Variable?

**Comment by Afar077** [comment]
I just logged on my HA and it worked!! I guess the issue was with the https instead of http... wow.. 

Thanks a lot for the help!!

**Comment by neilenns** [comment]
> I just logged on my HA and it worked!! I guess the issue was with the https instead of http... wow..
> 
> Thanks a lot for the help!!

Yep, that's what I was going to say next, I noticed it in your screenshot. Glad you got it working!

**Comment by neilenns** [comment]
> Just updated the docker but I don't have the new setting in my config. I'll have to add it manually. Do you have the name of the Variable?

Ooops forgot you were doing a direct Docker deployment. I updated the readme and sample docker-compose.yml file. The variable is `LOG_LEVEL`. Valid values are `error`, `warn`, `info`, `http`, and `debug`. The default is `info`.

**Comment by Afar077** [comment]
Ah nice! I added it and put in the value debug. It showed me what it was publishing to homeassistant.

Thanks!

**Comment by neilenns** [comment]
The weather station is trying to call /endpoint, which isn't correct. It should be trying to call /data.

Are you sure you configured the weather station properly?

**Comment by Afar077** [comment]
![image](https://github.com/neilenns/ambientweather2mqtt/assets/107782667/6f6961e1-ecbb-4ef8-8160-63df91778919)
Here's my config. No matter what I write as a server IP address, even a bogus 111.111.1.111, it gets the same Get /endpoint message on my log... 

Maybe my version of the weather station simply has an issue.

**Comment by neilenns** [comment]
Share the entire contents of the add on log

**Comment by Afar077** [comment]
2024-03-15T19:13:15.320Z [express] ::ffff:192.168.1.159 - - [15/Mar/2024:19:13:15 +0000] "GET /endpoint?&PASSKEY=8F96E9350F8D4A76693F34DFEBBB76A4&stationtype=WS1965B_V1.1.4&dateutc=2024-03-15+19:13:16&tempf=53.60&humidity=46&windspeedmph=0.00&windgustmph=0.00&maxdailygust=2.24&winddir=260&winddir_avg10m=127&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.000&yearlyrainin=0.000&totalrainin=0.000&battout=1&tempinf=57.38&humidityin=41&baromrelin=29.757&baromabsin=29.757 HTTP/1.1" 404 147

**Comment by neilenns** [comment]
That definitely looks like an issue with the weather station. I would try reaching out to Ambient Weather about it.
