### ISSUE TITLE
Add entity_category to sensors where appropriate

### ISSUE THREAD

**Issue by tankdeer** [neilenns/ambientweather2mqtt#129]
Typically speaking battery entities now have a `entity_category` of `diagnostic`. This allows them to show in the diagnostic section of the device. Consider adding to your sensor class, and setting as appropriate in here. 

Developer docs: https://developers.home-assistant.io/docs/core/entity/#registry-properties

_Originally posted by @tankdeer in https://github.com/neilenns/ambientweather2mqtt/pull/127#discussion_r1457820123_

**Comment by neilenns** [comment]
@tankdeer how are you deploying? Do you have an easy way to test this fix if it's in a Docker image that is tagged something other than "latest"?

**Comment by tankdeer** [comment]
Not really. I'm lazy and just run HAOS on bare metal and the community add-on.

**Comment by tankdeer** [comment]
I'll happily review the PR though

**Comment by neilenns** [comment]
> Not really. I'm lazy and just run HAOS on bare metal and the community add-on.

Same (well the HACS part)😅

**Comment by neilenns** [comment]
This is released. You can force an update in HA to grab it.

**Comment by tankdeer** [comment]
Looks good. Since I renamed a bunch of my sensors, I had to delete the batteries and rediscover them for the entity_category to get applied, but after that they are good

**Comment by neilenns** [comment]
I don't think it is the rename. I had to delete them too, I don't think HA refreshes the auto discovery when it changed and I've had no luck trying to delete the retained message.


________________________________

**Comment by tankdeer** [comment]
Ah, good to know. Thanks
