### ISSUE TITLE
observer 2.2.6 weather stations send garbage at the end of the query string

### ISSUE THREAD

**Issue by cybernard** [neilenns/ambientweather2mqtt#136]
GET /data/?MAC=11:22:33:44:55:66&stationtype=OBSERVERIP2_V2.2.6&dateutc=2023-12-07+01%3A07%3A10&tempf=35.96&humidity=81&windspeedmph=3.58&windgustmph=10.74&maxdailygust=14.76&winddir=30&winddir_avg10m=16&uv=0&solarradiation=0.00&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.378&monthlyrainin=0.677&yearlyrainin=9.638&totalrainin=9.638&battout=1&battrain=1&tempinf=69.08&humidityin=29&baromrelin=29.808&baromabsin=29.247&battin=1&temp2f=35.96&humidity2=81&batt2=1&lightning_day=9&lightning_time=1701904871&lightning_distance=14&batt_lightning=0&pm25=38.0&pm25_24h=29.1&aqi_pm25=107&aqi_pm25_24h=87&batt_25=1 **HTTP/1.1
Host:
Connection:close
User-Agent:OBSERVERIP2**

The information in bold is tacked on to the observer response and therefore confuses your addon.
 "HTTP/1.1 Host: connection:close User-Agent:OBSERVERIP2" is all garbage data added to the end of the response to the observer 2.

Please modify your addon to ignore everything after batt_25=1.

![289723045-ca90641b-dbd1-4d6b-b556-f9201aa16e60](https://github.com/neilenns/ambientweather2mqtt/assets/15042777/de6ce340-e44c-4003-ab9c-20cd3546b32c)

I got this hack but it only works once then closes.

**Comment by neilenns** [comment]
Please report this issue to Ambient Weather, they are sending an invalid GET request.

I tested this locally and what happens is the add-on gets a value of `1 HTTP/1.1 Host: Connection:close User-Agent:OBSERVERIP2` for the batt_25 value, which it then tries to convert to a number.

I'll have to do some thinking to see if there's a way to handle their mistake on my end.

**Comment by neilenns** [comment]
A fix for this is now released.

**Comment by cybernard** [comment]
In the debug area can you add the actual data received by your plug in?  It still isn't logging, and I feel like there still might be an extra space or misc symbol still present.

**Comment by neilenns** [comment]
If you set VERBOSE=true either via an environment variable or through the HA add-on UI it already logs the entire received request when it gets one. If that isn't showing anything then something is failing before my code even gets a chance to see it.

**Comment by cybernard** [comment]
I think your right about failing before your code gets a chance to see it.  I filed a support request with ambient weather to see what they say.

**Comment by neilenns** [comment]
I pushed a new release that adds some increased logging. You can now enable "http" level logging in the configuration for the add-on and that should show in the log the full GET request received by the underlying webserver before I get to process it.

**Comment by cybernard** [comment]
The data doesn't even reach your program.  I enabled http logging and nothing get logged.

**Comment by cybernard** [comment]
You would have to capture the data from a raw connection without a web server in the way.
