### ISSUE TITLE
New WS-1938 Built in CO2 sensor not handled

### ISSUE THREAD

**Issue by Lightning59** [neilenns/ambientweather2mqtt#160]
I just bought an Ambient WS-1938. This looks like its a brand new product for them. 

It has internal sensors for Temp, Humidity, barometric pressure and C02 ppm. I also currently have to WH31s paired to it as well.

All readings are working well, I get 3 temp, 3 humidity, 2 battery readings ( I haven't put backup batteries in the home station so maybe I'd get 3 battery readings if I'd done that) Plus the dewpoint reading plus the barometer.

The one item that is not showing up in MQTT (using MQTT Explorer) or home assistant is the internal CO2 sensor.

**Comment by Lightning59** [comment]
Here is  a log entry for whats coming over with logging set to http

`2024-06-01T16:37:09.976Z [express] ::ffff:[redacted ip] - - [01/Jun/2024:16:37:09 +0000] "GET /data/?&PASSKEY=[redacted]&stationtype=WS1938B_V1.2.9&dateutc=2024-06-01+16:37:09&winddir_avg10m=0&tempinf=83.66&humidityin=44&co2_in=1447&co2_in_24h=1289&baromrelin=30.132&baromabsin=30.132&temp1f=76.10&humidity1=52&batt1=1&temp8f=87.26&humidity8=46&batt8=1 HTTP/1.1" 200 2`

**Comment by neilenns** [comment]
This is now available in v4.8.0. To force HA to check for the new version:

1. Go to Settings > Add-ons > Add-on Store
2. Select ... in the top right
3. Select Check for Updates
