### ISSUE TITLE
Confirm that the device is pointing to the right battery for top level status

### ISSUE THREAD

**Issue by neilenns** [neilenns/ambientweather2mqtt#31]
It's auto reporting the battery state on the device list, how is it getting that? Is it from the batteryOk or batterOkCo2?

**Comment by danecreekphotography** [comment]
Are these used to set it?

```
'bat_lev_t':           'battery_level_topic',
'bat_lev_tpl':         'battery_level_template',
```

From https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by stovedoctor** [comment]
Mine showed up the same way co2

**Comment by neilenns** [comment]
Closing old issues
