### ISSUE TITLE
Provide support for arm architecture (Raspberry Pi)

### ISSUE THREAD

**Issue by philomatic** [neilenns/ambientweather2mqtt#64]
Hi there,

nice project! Unfortunately, by providing a docker image based on amd64 architecture this can't be used on arm processors like the Raspberry Pi has:

`ambientweather_1  | standard_init_linux.go:219: exec user process caused: exec format error`

Please consider providing a docker image for Raspberry users by using an arm based image too!

Best regards

**Comment by neilenns** [comment]
Docker Hub has decided to nuke my free ability to publish images (they seem to think I'm a corporate entity) :(

You should be able to make your own image pretty easily though. Looks like you just have to edit the `Dockerfile` and make the first line:

```
FROM arm32v6/node:14-alpine
```

**Comment by philomatic** [comment]
Thanks for the quick answer!

A `docker build - < Dockerfile` gives me:

```
Step 6/7 : RUN npm ci --no-optional
 ---> Running in b7fd85794770

#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x7e90d23c
The command '/bin/sh -c npm ci --no-optional' returned a non-zero code: 132
```

Any ideas?

**Comment by neilenns** [comment]
Make sure you've got the full GitHub repo on your local machine and then run `docker build .` from inside the root of the repo folder. I just gave it a try and it worked.

```
 ~\..\ambientweather2mqtt   main ≣ ~1 -0 !  docker build .                                        
[+] Building 236.4s (11/11) FINISHED
 => [internal] load build definition from Dockerfile                                              0.2s
 => => transferring dockerfile: 276B                                                              0.1s
 => [internal] load .dockerignore                                                                 0.1s
 => => transferring context: 2B                                                                   0.0s 
 => [internal] load metadata for docker.io/arm32v6/node:14-alpine                                 3.4s
 => [auth] arm32v6/node:pull token for registry-1.docker.io                                       0.0s
 => [1/5] FROM docker.io/arm32v6/node:14-alpine@sha256:93b39929a107b04b32986ecad7aa129e83d742f6  22.1s
 => => resolve docker.io/arm32v6/node:14-alpine@sha256:93b39929a107b04b32986ecad7aa129e83d742f63  0.0s 
 => => sha256:93b39929a107b04b32986ecad7aa129e83d742f63c47b4ceb083c8756181d5dc 1.16kB / 1.16kB    0.0s 
 => => sha256:74a835d2043a61209d132aae4cb35803b69409cbdbeb3fc6bbc699cb59b38194 6.55kB / 6.55kB    0.0s 
 => => sha256:56afcfda5d78cc243287acbaad250c5e8c0f47aae620dd7c51985b0d3c9b2728 2.64MB / 2.64MB    1.1s 
 => => sha256:03985287d6eff0c54231c34cd2153695ec8b01b85046f0d8281abb0d06807d7 35.74MB / 35.74MB  11.7s 
 => => sha256:bdafec0e0e4edf1a3afde9a477b672f8a2f7b7280fb4fa6926b12b3318f02430 2.42MB / 2.42MB    2.1s
 => => extracting sha256:56afcfda5d78cc243287acbaad250c5e8c0f47aae620dd7c51985b0d3c9b2728         0.6s 
 => => sha256:4c90cdcefbbcece3f2f691359344e46d332a2b3bd153a544ed10c9dc1427c723 450B / 450B        1.6s 
 => => extracting sha256:03985287d6eff0c54231c34cd2153695ec8b01b85046f0d8281abb0d06807d72         7.7s
 => => extracting sha256:bdafec0e0e4edf1a3afde9a477b672f8a2f7b7280fb4fa6926b12b3318f02430         0.6s 
 => => extracting sha256:4c90cdcefbbcece3f2f691359344e46d332a2b3bd153a544ed10c9dc1427c723         0.0s
 => [internal] load build context                                                                87.1s 
 => => transferring context: 114.73MB                                                            87.1s 
 => [2/5] RUN mkdir -p /home/node/app && chown -R node:node /home/node/app                        3.1s 
 => [3/5] WORKDIR /home/node/app                                                                  0.2s 
 => [4/5] COPY --chown=node:node . .                                                              1.4s 
 => [5/5] RUN npm ci --no-optional                                                              141.8s 
 => exporting to image                                                                            2.2s 
 => => exporting layers                                                                           2.2s 
 => => writing image sha256:c06eaf8146bc7f088275686302fb82d698b0624d7c3f2611783fbd5c46291209      0.0s
```

**Comment by neilenns** [comment]
Figured out how to push to GitHub instead of Docker for a package repository. Trying to get this going as a multi-platform image now.

**Comment by neilenns** [comment]
Ok I think I got this done @philomatic. Change your `docker-compose.yml` file to pull this image tag instead:

```yaml
image: ghcr.io/neilenns/ambientweather2mqtt:latest
``` 

That should Just Work(tm). [Updated sample file](https://github.com/neilenns/ambientweather2mqtt/blob/main/sampleConfiguration/docker-compose.yml) is available as well.

**Comment by philomatic** [comment]
Hi neil,

finally I've found some time to check into this:

thanks for providing cross-platform docker images! Unfortunately, this does no solve the problem. It's not (only) a platform issue at all!

node:14-alpine (latest) is based on the alpine3.14 image, which is incompatible with the libseccomp2 version on Raspbian Buster:
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.13.0#time64_requirements

For anyone stumbling on this issue too, here are two workarounds:

1. Upgrade libseccomp2 via backport:
https://blog.samcater.com/fix-workaround-rpi4-docker-libseccomp2-docker-20/

2. Use alpine3.12 instead in Dockerfile:
`FROM arm32v6/node:14-alpine3.12`

Best regards
Patrick

**Comment by neilenns** [comment]
Thanks for figuring that out @philomatic, I never in a million years would have found that.

New release pushed with a change to the base image version. Should be good to go at this point, let me know how it works out.

**Comment by philomatic** [comment]
Works like a charm!

Best regards
