### ISSUE TITLE
Feature request - Change manual docker setup to Community Add-on

### ISSUE THREAD

**Issue by tankdeer** [neilenns/ambientweather2mqtt#73]
This looks like a great option (And FYI, you can configure locally on Android now as well), however the manual docker setup could be a turnoff to many people. Have you considered setting this up as a community add-on? Those are essentially docker containers anyways, so hopefully it wouldn't be too difficult, but it would allow easy access to your tool to a lot more users

Thanks

**Comment by neilenns** [comment]
Do you have a link handy on how to set up a community add-on? I did some quick searching and came up empty handed :(

**Comment by tankdeer** [comment]
Sadly I don't, but I can do some research and see what I come up with

**Comment by tankdeer** [comment]
Sorry for the delay. Here's the official documentation: https://developers.home-assistant.io/docs/add-ons/

**Comment by neilenns** [comment]
Thanks! I took a look through it and it's more work than I'm willing to put in for what was a little side project for me. I'll leave this issue open for a bit in case someone else comes along and is interested in opening a PR with the necessary changes, but honestly that's unlikely.

**Comment by tankdeer** [comment]
> I think I might have this in a workable state but not really sure, you can try testing it in your HA setup by adding the repo https://github.com/NickM-27/ambientweather2mqtt/tree/addon

Thanks for that. I was actually going to attempt to do the same thing later today or tomorrow, but you beat me to it.

Unfortunately, HA won't let me add it as a repo. I think the issue is that you're  missing a `repository.yaml` in the root level of the repo, as indicated here: https://developers.home-assistant.io/docs/add-ons/repository

**Comment by NickM-27** [comment]
Oops, added. This would likely be more optimal as its own repo but should work either way

**Comment by tankdeer** [comment]
Still nothing unfortunately. I wonder if it needs to be merged into the main branch? That's the only thing that comes to mind

**Comment by NickM-27** [comment]
Does it throw an error? I'd think it would work but maybe not

**Comment by NickM-27** [comment]
@tankdeer Okay I merged it to main of my repo so can try that: https://github.com/NickM-27/ambientweather2mqtt

> Oooh I go kayaking and come back to progress! I will happily merge this if you guys can figure out the above remaining issue.

Cool, hopefully we can get the remaining things sorted out

**Comment by tankdeer** [comment]
Some progress. I was able to add the repository. However, it doesn't show any available add-ons. I'm trying to read more and see if something's missing

**Comment by NickM-27** [comment]
It's missing an icon, not sure if that would affect it

Also I didn't change the URLs which point to this repo so that might be an issue too

**Comment by tankdeer** [comment]
I don't think the URL is the issue. I'm looking at another custom repo and it doesn't even have one. I wouldn't suspect something as simple as the icon to do it, but who knows at this point.

**Comment by tankdeer** [comment]
So one thing that is contributing, although I don't know if it's the sole issue. I am running on an Intel NUC, and the i386 is not listed under supported arch in config.yaml. I added a note to the PR as well

**Comment by NickM-27** [comment]
Okay added all archs so should be able to give it another try

**Comment by tankdeer** [comment]
Unfortunately still not showing for me. I assume this is working fine for you? It must be something on my end?

**Comment by NickM-27** [comment]
I run everything in native docker and don't really have a great way to test addons. They have the supervisor vscode dev container so I can spin that up but it's a bit of a chore, probably will need to to see what's up exactly

**Comment by tankdeer** [comment]
Fair enough. I'm definitely at a bit of a loss at this point. Based on the documentation and comparing to other addons, it looks like everything is there.

**Comment by NickM-27** [comment]
Okay should be good now, had some config validation issues and other stuff that would have kept it from running

**Comment by tankdeer** [comment]
Thanks. I was messing with this yesterday, but I am far from a Docker expert, so it was slow going. I did realize the reason I couldn't install it was due to the PORT environment variable declaration, which you fixed.

Anyways, I can install and config now. However, it won't start due to the ENV variables  not being passed, which based on your PR comments you saw coming.

```
2022-06-09T11:59:55-07:00 [Main] Starting up
2022-06-09T11:59:55-07:00 [Main] The MQTT_SERVER environment variable isn't set. It must be set to the URL for the MQTT server, e.g. http://192.168.1.1/.
2022-06-09T11:59:55-07:00 [Main] Error: Required environment variables are missing, startup halted. Add the missing environment variables then run again.
```

I wonder if some of these things (Like the MQTT info) could be moved away from ENV variables and passed as runtime arguments. It would require changing `mqttManager.ts `but might be easier long term

**Comment by tankdeer** [comment]
Yeah, I have all the options populated. However it doesn't look like they're getting propagated to the process. The errors are coming from validation in `main.ts`. I suspect the parsing of the options in `startup.sh` isn't working as expected

**Comment by NickM-27** [comment]
Silly me I was setting command and not overriding entrypoint so it was being ignored. I have it almost working now, this should definitely be doable as is

**Comment by NickM-27** [comment]
Try it now, should be working

**Comment by tankdeer** [comment]
Getting closer. Exception caught during startup. Logs:

```
2022-06-09T15:12:55-07:00 [Main] Starting up
2022-06-09T15:12:55-07:00 [Main] SyntaxError: Unexpected token u in JSON at position 0
```

A quick search online implies it's from parsing an undefined property. I am wondering if it's from MQTT_REJECT_UNAUTHORIZED not being set

**Comment by NickM-27** [comment]
> A quick search online implies it's from parsing an undefined property. I am wondering if it's from MQTT_REJECT_UNAUTHORIZED not being set

Hadn't thought of that, will add that one too

**Comment by NickM-27** [comment]
Okay should be good now

**Comment by tankdeer** [comment]
Getting closer. So I can install, configure, and start the add-on. It's running, and there's no errors in the log. However, there's no device or entities created. Looking at MQTT Explorer, I don't see anything coming across, _except_ the "online" status for the availability topic.

**Comment by NickM-27** [comment]
Is the weather station pointing at the instance correctly and the exposed port and PORT variable are matching (as well as matching the one the station is pointing at)

**Comment by tankdeer** [comment]
As per the original instructions, yeah, I think everything is OK. Unless this being an add-on changes any of that

![image](https://user-images.githubusercontent.com/48227886/172965852-b8554f94-aed8-4651-b4bf-9e9a16608674.png)

Add-on config options
```
STATION_MAC_ADDRESS: 50:02:91:**:**:**
MQTT_SERVER: http://192.168.30.10
MQTT_USERNAME: homeassistant
MQTT_PASSWORD: **********************
MQTT_REJECT_UNAUTHORIZED: false
TZ: America/Los_Angeles
PORT: '8123'
```

Add-on port is also the default 8123

**Comment by NickM-27** [comment]
@neilenns I'm not sure if this is due to a change I made or something else, do you see anything obvious?

**Comment by tankdeer** [comment]
I wouldn't be surprised if it's something on my end, but hell if I know what.

**Comment by neilenns** [comment]
It's been so long since I touched this 😬

I just looked at my HA install and it looks like I'm getting "unknown" for all of my entities. Hmm. Looked in MQTT Explorer and I don't see any `status` messages coming through. This is my Docker image running as it has been since I published the initial release.

I nuked the Docker image and restarted it and... nothing is coming through to MQTT at all. Not a single message :(

**Comment by NickM-27** [comment]
It's been working for me on my Unraid server fwiw

**Comment by tankdeer** [comment]
I wonder if something has changed in the firmware since you originally wrote this. I was looking at another integration previously, that worked, but liked the idea of yours better. This is the current protocol doc: https://ambientweather.com/faqs/question/view/id/1857/

My symptoms sound exactly like yours, except my availability is showing `online`

**Comment by neilenns** [comment]
@tankdeer I think the weather station is no longer talking to my service is what's happening. I'll have to try configuring it again.

**Comment by neilenns** [comment]
Or... it's talking to my Docker instance and not my debugging laptop lol.

**Comment by tankdeer** [comment]
Happy to help in any way that I can - just let me know. In either case, it doesn't seem related to the PR @NickM-27 opened, and I'd think that could be merged.

**Comment by neilenns** [comment]
Ok I'm back up and running, the original thing is working fine. Not sure why I was having so much trouble. @tankdeer enable verbose logging (was that set up as an available option @NickM-27?) and make sure that you see incoming data from the weather station.

**Comment by tankdeer** [comment]
Log level wasn't setup as a configurable option, and unless I'm mistaken, I can't set it for add-ons in the main HA configuration (only integrations).

**Comment by NickM-27** [comment]
Verbose is now an option and should be usable now

**Comment by tankdeer** [comment]
Sorry for the delay. Installed the latest version and enabled verbose logging. Sadly, not a single additional thing was logged. The last line in my log file is the `Listening at http://localhost:8123` during the webserver startup

**Comment by neilenns** [comment]
That means there's no calls from AW getting through. Do you have a firewall that might be blocking it?


________________________________

**Comment by tankdeer** [comment]
Shouldn't be. AW & HA are both on the same VLAN, with no firewall rules blocking them. I was also playing with a different local AD add-on (https://github.com/tlskinneriv/awnet_local), and I get messages there. 

Could it be something with the port mapping of the container? I wouldn't think so, but what do I know, lol.

Actually, I just noticed in MQTT Manager that upon starting the add-on, I do get a (partial?) discovery of utcDate. It appears to just be an empty payload published to it's discovery topic. Digging through your code, there should definitely be some verbose logging accompanying it, so I have no idea where it's coming from

**Comment by neilenns** [comment]
@NickM-27 I gave this a try by pointing to your repo on my Home Assistant server and can confirm that something isn't right with the networking/port.

By default the config uses 8123 for the port which conflicts with the port I run Home Assistant on. I used the config UI to change it to 8555 and that still didn't help. I can't hit `http://homeassistant:8555`, I get a connection refused message.

**Comment by NickM-27** [comment]
@neilenns  just making sure you changed both the port variable and the port mapping right?

**Comment by neilenns** [comment]
@NickM-27 I only changed the port variable at the bottom of the config screen. I assumed the port mapping for my code didn't have to change since this is Docker and it would map the external port to the internal `8132` port?

**Comment by NickM-27** [comment]
I misunderstood the docker env PORT to be a variable (since in the docker compose file it shows port on both sides instead of {PORT}:8132

Either way, you should see in HA there's a port variable and further down there's the port mapping 8132 tcp) so will need that one to be changed.

**Comment by neilenns** [comment]
It doesn't work, even if I do this:

![image](https://user-images.githubusercontent.com/9524118/173233098-96a34508-ceb9-4028-b238-04035d6e18ad.png)

I still can't hit http://homeassistant:8555

**Comment by NickM-27** [comment]
PORT under options does nothing, it was a misinterpretation from me. 

PORT under network is the port mapping from `HomeAssisant Host`:port_var <-> `ambientweather2mqtt docker`:8123

**Comment by NickM-27** [comment]
I need to remove the PORT from options and whatever you set the network port to is what ambient weather needs to point to

**Comment by tankdeer** [comment]
Are you sure? It sure looks like port under options is used for the webserver for the AW requests. There's a try/catch block which opens the connection in `webServer.start()`

```
  try {
    server = app.listen(process.env.PORT, () =>
      log.info("Web server", `Listening at http://localhost:${process.env.PORT}`),
    );
    httpTerminator = createHttpTerminator({
      server,
    });
  } catch (e) {
    throw new Error(`Unable to start web server: ${e.error}`);
  }
```

Unless I overlooked the port env variable being overwritten somewhere, your `startup.sh` script would export it as whatever is entered in the options

**Comment by NickM-27** [comment]
> Are you sure? It sure looks like port under options is used for the webserver for the AW requests. There's a try/catch block which opens the connection in `webServer.start()`
> 
> ```
>   try {
>     server = app.listen(process.env.PORT, () =>
>       log.info("Web server", `Listening at http://localhost:${process.env.PORT}`),
>     );
>     httpTerminator = createHttpTerminator({
>       server,
>     });
>   } catch (e) {
>     throw new Error(`Unable to start web server: ${e.error}`);
>   }
> ```
> 
> Unless I overlooked the port env variable being overwritten somewhere, your `startup.sh` script would export it as whatever is entered in the options

Per https://github.com/neilenns/ambientweather2mqtt/issues/73#issuecomment-1153027312 I understood that the PORT variable wasn't needed, seems there is definitely some confusion going on here. But based on the code it does seem both of them need to be in there and need to be the same value (not 8132).

**Comment by tankdeer** [comment]
Can confirm that I'm confused, lol.

Unfortunately I've tried a myriad of different port configurations and none seem to work. And I get no additional verbose logging as it seems like none of those log lines are hit until after we connect to the web server

**Comment by neilenns** [comment]
If this is using Docker there's two different port numbers at play, at least based on my past Docker experience:

1. The port number that's used inside the Docker container by services. This is the one that's set via the env variable and what the code uses to listen for incoming calls from the weather station.
2. The port number that's exposed to the world for connections. This can be different and incoming connections on that port get mapped by Docker to the port expected internally by the urnning code. I assume that's what the port in the config.yaml is, however that is HA config stuff and not a Docker config file so I'm not sure how it gets passed/used by Docker.

**Comment by NickM-27** [comment]
Gotcha, most docker containers I've worked on the internal port is just static and not configurable and port mapping is being used. I think I may hardcore this so it works that way so it is less confusing to users.

I'll re-read the docs and update the PR as I think I understand this better now

**Comment by NickM-27** [comment]
@tankdeer Okay try pulling again, default port will be 7000 which is what you will want to point your weather station at, it is hard set to use 8132 internally 👍 

Should work as expected now

**Comment by NickM-27** [comment]
> @NickM-27 If you hardcode it internally that's a breaking change for existing users who might have changed the port, right?

No, I am setting the `PORT` variable as 8132 and then there is the port mapping which by default maps host:7000 <-> internal:8132

Users can change the 7000 to whatever they want. I honestly don't see a reason why a user would need to change the port that is used internally

**Comment by tankdeer** [comment]
Hot diggity daffodil!

```
2022-06-14T14:46:25-07:00 [Main] Starting up
2022-06-14T14:46:25-07:00 [MQTT] Connected to MQTT server http://192.168.30.10
2022-06-14T14:46:25-07:00 [Web server] Listening at http://localhost:8132
2022-06-14T14:46:26-07:00 [Weather handler] /data/?stationtype=AMBWeatherV4.3.3&PASSKEY=50:02:91:00:00:00&dateutc=2022-06-14+21:46:24&tempinf=69.1&humidityin=42&baromrelin=30.018&baromabsin=29.988&tempf=61.9&battout=1&humidity=53&winddir=245&windspeedmph=2.0&windgustmph=2.2&maxdailygust=13.6&hourlyrainin=0.000&eventrainin=0.118&dailyrainin=0.071&weeklyrainin=0.248&monthlyrainin=4.480&totalrainin=97.673&solarradiation=758.73&uv=7&batt_co2=1
2022-06-14T14:46:26-07:00 [Weather handler] {
  "stationtype": "AMBWeatherV4.3.3",
  "PASSKEY": "50:02:91:00:00:00",
  "dateutc": "2022-06-14 21:46:24",
  "tempinf": "69.1",
  "humidityin": "42",
  "baromrelin": "30.018",
  "baromabsin": "29.988",
  "tempf": "61.9",
  "battout": "1",
  "humidity": "53",
  "winddir": "245",
  "windspeedmph": "2.0",
  "windgustmph": "2.2",
  "maxdailygust": "13.6",
  "hourlyrainin": "0.000",
  "eventrainin": "0.118",
  "dailyrainin": "0.071",
  "weeklyrainin": "0.248",
  "monthlyrainin": "4.480",
  "totalrainin": "97.673",
  "solarradiation": "758.73",
  "uv": "7",
  "batt_co2": "1"
}
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for barometricPressureAbsolute.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for barometricPressureRelative.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for batteryCo2Ok.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for batteryOk.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for eventDate.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for humidityIndoor.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for humidityOutdoor.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainDaily.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainEvent.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainHourly.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainMonthly.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainTotal.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for rainWeekly.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for solarRadiation.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for temperatureIndoor.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for temperatureOutdoor.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for windDirection.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for windGust.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for windMaxDailyGust.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for windSpeed.
2022-06-14T14:46:26-07:00 [Sensor] Publishing discovery for uv.
```

The port mapping was definitely the issue

**Comment by neilenns** [comment]
> > @NickM-27 If you hardcode it internally that's a breaking change for existing users who might have changed the port, right?
> 
> No, I am setting the `PORT` variable as 8132 and then there is the port mapping which by default maps `host:7000 <-> internal:8132`
> 
> Users can change the 7000 to whatever they want. I honestly don't see a reason why a user would need to change the port that is used internally

Ah I get it, this wouldn't impact anyone using the .env file directly. It's just getting set to 7000 when you generate the .env file from the HA config values.

**Comment by neilenns** [comment]
Fixed by https://github.com/neilenns/ambientweather2mqtt/pull/75
