### ISSUE TITLE
Extra sensors temperature not being sent to MQTT

### ISSUE THREAD

**Issue by Doonga** [neilenns/ambientweather2mqtt#90]
I have a WS-5000 station with a few extra temperature sensors. I can see all of the data from the sensors aside from the temperature. I captured the request from the station to the docker container and I can see that the data is there. Here's an example from tcpdump:

`GET /data/?stationtype=AMBWeatherV4.3.3&PASSKEY=<removed>&dateutc=2022-09-16+15:29:06&tempinf=63.3&battin=1&humidityin=59&baromrelin=29.510&baromabsin=29.510&tempf=62.2&battout=1&battrain=1&humidity=56&winddir=261&winddir_avg10m=327&windspeedmph=0.0&windspdmph_avg10m=1.6&windgustmph=2.2&maxdailygust=6.3&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.890&monthlyrainin=3.110&yearlyrainin=18.520&lightning_day=0&lightning_time=1663113495&lightning_distance=20&batt_lightning=0&solarradiation=561.48&uv=5&soilhum1=23&battsm1=1&temp1f=63.7&humidity1=58&temp2f=63.9&humidity2=54&temp3f=72.5&humidity3=40&temp4f=59.4&humidity4=64&batt1=1&batt2=1&batt3=1&batt4=1&batt_co2=1 HTTP/1.1`

The `&temp#f` parameters have the data, but it doesn't seem to make it over to MQTT.

**Comment by neilenns** [comment]
@Doonga Thanks for reporting this. I think I fixed it but don't have any way to test. New release is generating, give it about 15-20 minutes then pull the latest Docker image and see if it works.

**Comment by Doonga** [comment]
Looks good, thank for the very fast turnaround!

**Comment by neilenns** [comment]
It worked ok?

**Comment by Doonga** [comment]
Yep, worked perfectly!

**Comment by neilenns** [comment]
Woo!!!!!!!!!!!!!!!!!!!!!!!!!
